using Microsoft.AspNetCore.Mvc;
using JobBank1111.Job.WebAPI.Contract.AutoGenerated;
using CSharpFunctionalExtensions;

namespace JobBank1111.Job.WebAPI.{Feature};

/// <summary>
/// {Feature} Controller
/// </summary>
/// <remarks>
/// 此 Controller 實作自動產生的 I{Feature}Api 介面
/// 職責：
/// - HTTP 請求/回應處理
/// - 路由管理
/// - Result Pattern 轉換為 HTTP 狀態碼
/// - 請求驗證（透過 FluentValidation 或 DataAnnotations）
/// </remarks>
[ApiController]
[Route("api/v1/[controller]")]
public class {Feature}Controller(
    {Feature}Handler handler,
    ILogger<{Feature}Controller> logger) : ControllerBase, I{Feature}Api
{
    /// <summary>
    /// 建立新的 {Resource}
    /// </summary>
    /// <param name="request">建立請求</param>
    /// <param name="cancellationToken">取消權杖</param>
    /// <returns>建立成功的 {Resource} 資料</returns>
    public async Task<IActionResult> Create{Resource}(
        Create{Resource}Request request,
        CancellationToken cancellationToken = default)
    {
        logger.LogInformation("開始建立 {Resource}：{RequestData}",
            System.Text.Json.JsonSerializer.Serialize(request));

        // 呼叫 Handler 處理業務邏輯
        var result = await handler.Create{Resource}Async(request, cancellationToken);

        // 使用 Match 方法轉換 Result 為 HTTP 回應
        return result.Match(
            success =>
            {
                logger.LogInformation("{Resource} 建立成功：{Id}", success.Id);

                // 201 Created - 包含 Location 標頭
                return CreatedAtAction(
                    nameof(Get{Resource}ById),
                    new { id = success.Id },
                    success);
            },
            failure =>
            {
                logger.LogWarning("{Resource} 建立失敗：{Code} - {Message}",
                    failure.Code, failure.Message);

                // 根據 FailureCode 映射 HTTP 狀態碼
                var statusCode = FailureCodeMapper.ToHttpStatusCode(failure.Code);
                return StatusCode(statusCode, failure);
            });
    }

    /// <summary>
    /// 根據 ID 查詢 {Resource}
    /// </summary>
    /// <param name="id">{Resource} 唯一識別碼</param>
    /// <param name="cancellationToken">取消權杖</param>
    /// <returns>{Resource} 詳細資料</returns>
    public async Task<IActionResult> Get{Resource}ById(
        Guid id,
        CancellationToken cancellationToken = default)
    {
        logger.LogInformation("查詢 {Resource}：{Id}", id);

        var result = await handler.Get{Resource}ByIdAsync(id, cancellationToken);

        return result.Match(
            success =>
            {
                logger.LogInformation("{Resource} 查詢成功：{Id}", id);
                return Ok(success); // 200 OK
            },
            failure =>
            {
                logger.LogWarning("{Resource} 查詢失敗：{Code} - {Message}",
                    failure.Code, failure.Message);

                var statusCode = FailureCodeMapper.ToHttpStatusCode(failure.Code);
                return StatusCode(statusCode, failure);
            });
    }

    /// <summary>
    /// 更新 {Resource}
    /// </summary>
    /// <param name="id">{Resource} 唯一識別碼</param>
    /// <param name="request">更新請求</param>
    /// <param name="cancellationToken">取消權杖</param>
    /// <returns>更新後的 {Resource} 資料</returns>
    public async Task<IActionResult> Update{Resource}(
        Guid id,
        Update{Resource}Request request,
        CancellationToken cancellationToken = default)
    {
        logger.LogInformation("更新 {Resource}：{Id}", id);

        var result = await handler.Update{Resource}Async(id, request, cancellationToken);

        return result.Match(
            success =>
            {
                logger.LogInformation("{Resource} 更新成功：{Id}", id);
                return Ok(success); // 200 OK
            },
            failure =>
            {
                logger.LogWarning("{Resource} 更新失敗：{Code} - {Message}",
                    failure.Code, failure.Message);

                var statusCode = FailureCodeMapper.ToHttpStatusCode(failure.Code);
                return StatusCode(statusCode, failure);
            });
    }

    /// <summary>
    /// 刪除 {Resource}
    /// </summary>
    /// <param name="id">{Resource} 唯一識別碼</param>
    /// <param name="cancellationToken">取消權杖</param>
    /// <returns>刪除結果</returns>
    public async Task<IActionResult> Delete{Resource}(
        Guid id,
        CancellationToken cancellationToken = default)
    {
        logger.LogInformation("刪除 {Resource}：{Id}", id);

        var result = await handler.Delete{Resource}Async(id, cancellationToken);

        return result.Match(
            success =>
            {
                logger.LogInformation("{Resource} 刪除成功：{Id}", id);
                return NoContent(); // 204 No Content
            },
            failure =>
            {
                logger.LogWarning("{Resource} 刪除失敗：{Code} - {Message}",
                    failure.Code, failure.Message);

                var statusCode = FailureCodeMapper.ToHttpStatusCode(failure.Code);
                return StatusCode(statusCode, failure);
            });
    }

    /// <summary>
    /// 分頁查詢 {Resource} 列表
    /// </summary>
    /// <param name="pageIndex">頁碼（從 0 開始）</param>
    /// <param name="pageSize">每頁筆數</param>
    /// <param name="cancellationToken">取消權杖</param>
    /// <returns>{Resource} 分頁列表</returns>
    public async Task<IActionResult> Get{Resource}List(
        int pageIndex = 0,
        int pageSize = 10,
        CancellationToken cancellationToken = default)
    {
        logger.LogInformation("查詢 {Resource} 列表：PageIndex={PageIndex}, PageSize={PageSize}",
            pageIndex, pageSize);

        var result = await handler.Get{Resource}ListAsync(pageIndex, pageSize, cancellationToken);

        return result.Match(
            success =>
            {
                logger.LogInformation("{Resource} 列表查詢成功：共 {TotalCount} 筆",
                    success.TotalCount);
                return Ok(success); // 200 OK
            },
            failure =>
            {
                logger.LogWarning("{Resource} 列表查詢失敗：{Code} - {Message}",
                    failure.Code, failure.Message);

                var statusCode = FailureCodeMapper.ToHttpStatusCode(failure.Code);
                return StatusCode(statusCode, failure);
            });
    }
}

/* 使用說明
 *
 * 1. 替換佔位符：
 *    - {Feature}：功能名稱（例如：Member、Product、Order）
 *    - {Resource}：資源名稱（例如：Member、Product、Order）
 *
 * 2. 範例替換：
 *    {Feature} = Member
 *    {Resource} = Member
 *
 *    產生結果：
 *    - namespace JobBank1111.Job.WebAPI.Member
 *    - public class MemberController
 *    - Task<IActionResult> CreateMember(CreateMemberRequest request, ...)
 *
 * 3. 核心原則：
 *    ✅ Controller 職責：
 *       - HTTP 請求/回應轉換
 *       - Result Pattern 處理
 *       - HTTP 狀態碼映射
 *       - 結構化日誌記錄
 *
 *    ❌ Controller 不應該：
 *       - 包含業務邏輯（交給 Handler）
 *       - 直接存取資料庫（交給 Repository）
 *       - 拋出業務例外（使用 Result Pattern）
 *
 * 4. Result Pattern 處理：
 *    - 使用 Match 方法轉換 Result<TSuccess, Failure> 為 IActionResult
 *    - Success 路徑：回傳適當的 HTTP 狀態碼（200, 201, 204）
 *    - Failure 路徑：使用 FailureCodeMapper 映射錯誤碼為 HTTP 狀態碼
 *
 * 5. HTTP 狀態碼映射：
 *    - 201 Created：建立成功（包含 Location 標頭）
 *    - 200 OK：查詢、更新成功
 *    - 204 No Content：刪除成功
 *    - 400 Bad Request：驗證錯誤（ValidationError）
 *    - 401 Unauthorized：未授權（Unauthorized）
 *    - 404 Not Found：資源不存在（NotFound）
 *    - 409 Conflict：資源衝突（DuplicateEmail、DbConcurrency）
 *    - 500 Internal Server Error：系統錯誤（DbError、InternalServerError）
 *
 * 6. 日誌記錄：
 *    - LogInformation：記錄正常操作（開始、成功）
 *    - LogWarning：記錄業務失敗（但不是系統錯誤）
 *    - LogError：由 ExceptionHandlingMiddleware 統一處理系統例外
 *
 * 7. 依賴注入：
 *    - 使用主建構函式（C# 12）
 *    - 注入 Handler 處理業務邏輯
 *    - 注入 ILogger 記錄日誌
 *
 * 8. CancellationToken：
 *    - 所有非同步方法都應支援 CancellationToken
 *    - 傳遞給 Handler 和 Repository
 *    - 支援請求取消與逾時處理
 */
